### ISSUE TITLE
编辑器的Markdown格式无效，发送给后端的请求会自动加上<p>标签导致Markdown无效

### ISSUE THREAD

**Issue by 371091997** [Thecosy/IceCMS#12]
![录屏_选择区域_20230508151901](https://user-images.githubusercontent.com/26164116/236760425-1811d401-d5cd-46d5-96c9-04fc8b08fb1c.gif)

**Comment by Thecosy** [comment]
Markdown编辑器用的是[TinyMCE](https://www.tiny.cloud/)不知道换成其他的行不行

**Comment by 371091997** [comment]
不清楚Tinymce为什么会这样，我替换成了mavon-editor就可以了
