### ISSUE TITLE
IceWk-uniApp 小程序hbuilder下载依赖失败

### ISSUE THREAD

**Issue by longzb2008** [Thecosy/IceCMS#22]
项目 'IceWk-uniApp' 开始编译...
 请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用cli发布命令进行发布
 小程序各家浏览器内核及自定义组件实现机制存在差异，可能存在样式布局兼容问题，参考：https://uniapp.dcloud.io/matter?id=mp
 正在编译中...
 ​Browserslist: caniuse-lite is outdated. Please run:
   npx update-browserslist-db@latest
   Why you should do it regularly: https://github.com/browserslist/update-db#readme​
 at subPage/commen/post.vue:1
 Module build failed (from ./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js):
 Error: 组件 bgyxedit 引用错误，仅支持 import 方式引入组件
     at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/webpack-uni-mp-loader/lib/babel/util.js:38:13
     at Array.forEach (<anonymous>)
     at parseComponents (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/webpack-uni-mp-loader/lib/babel/util.js:32:9)
![CleanShot 2024-03-18 at 2  32 11](https://github.com/Thecosy/IceCMS/assets/16234591/ea72cb88-7585-491a-8d87-6c973b09fb74)

**Comment by likaia** [comment]
我也遇到这个问题了，你解决了没

**Comment by Thecosy** [comment]
已发布新版本uniapp
