### ISSUE TITLE
提交商品时 addtime 字段错误不匹配

### ISSUE THREAD

**Issue by jackzhao12345** [Thecosy/IceCMS#4]
msg: "nested exception is org.apache.ibatis.reflection.ReflectionException: Could not set property 'updateTime' of 'class com.ttice.icewkment.entity.Resource' with value 'Fri Dec 16 09:12:59 UTC 2022' Cause: java.lang.IllegalArgumentException: argument type mismatch"

前端传的时间对的，以及数据库，需要改一下后端

**Comment by Thecosy** [comment]
时间改为bollean了。
