### ISSUE TITLE
There is unauthorized access to the API, resulting in the disclosure of sensitive information

### ISSUE THREAD

**Issue by topdayplus** [Thecosy/IceCMS#7]
This api does not require login, obtains user information through user_id, and returns the user name, password, and email address in plain text.

![02](https://user-images.githubusercontent.com/35645904/235364459-98f11a8f-769d-48f9-8411-d6a117a22e2e.png)

It is like the preview address provided by the project, macwk.cc, and the backend service address is macwk.cc/api through the request body. So we can get any user information, including the administrator.

![03](https://user-images.githubusercontent.com/35645904/235364490-71927447-187a-43b6-ba3f-ba25026d854b.png)

![04](https://user-images.githubusercontent.com/35645904/235364493-ab8e6cc2-3324-46a9-b72e-cdb035b35c2b.png)

**Comment by Thecosy** [comment]
Sorry, this interface is the interface for the foreground to obtain other user information. It is open. I will authenticate him in the next version. And hide key information. thank you for your support
